### ISSUE TITLE
Atheros Killer E2400 need help

### ISSUE THREAD

**Issue by arizuka** [AndiWeiss/alx-wol#17]
I'm a newbie about Linux, my trouble wasn't even call a issue, but I really need help. and my native language is not English. if my words seems not politely, I'm sorry for that, I didn't mean it.

I have a NIC on a motherboard which model is Atheros Killer E2400, I was try install Proxmox Virtual Environment version 8 on this computer, and I got a not supported feedback:
```
root@pve:~# ethtool enp1s0
Settings for enp1s0:
	Supported ports: [ TP ]
	Supported link modes:   10baseT/Half 10baseT/Full
	                        100baseT/Half 100baseT/Full
	                        1000baseT/Full
	Supported pause frame use: Symmetric Receive-only
	Supports auto-negotiation: Yes
	Supported FEC modes: Not reported
	Advertised link modes:  10baseT/Half 10baseT/Full
	                        100baseT/Half 100baseT/Full
	                        1000baseT/Full
	Advertised pause frame use: Symmetric
	Advertised auto-negotiation: Yes
	Advertised FEC modes: Not reported
	Speed: 100Mb/s
	Duplex: Full
	Auto-negotiation: on
	Port: Twisted Pair
	PHYAD: 0
	Transceiver: internal
	MDI-X: Unknown
        Current message level: 0x000060e4 (24804)
                               link ifup rx_err tx_err hw wol
	Link detected: yes
``` 

I read two topics, like:
https://bugzilla.kernel.org/show_bug.cgi?id=61651#c55
https://www.linuxquestions.org/questions/slackware-14/alx-wol-working-in-6-1-x-4175722247/#post6518786

But I still get no idea how to patch this project in my system.
first I was downgrade PVE kernel to 6.1, because there seems only linux-source-6.1 is in the PVE source.
```
root@pve:~# apt search linux-source-
Sorting... Done
Full Text Search... Done
linux-source-6.1/stable 6.1.106-3 all [upgradable from: 6.1.99-1]
  Linux kernel source for version 6.1 with Debian patches

root@pve:~# pveversion -v
proxmox-ve: 8.2.0 (running kernel: 6.1.10-1-pve)
......
```

Than, I was installed dkms, and wget source files of this project on this computer, got these files:
```
root@pve:~# ls /usr/src/linux-source-6.1/drivers/net/ethernet/atheros/alx
alx.h  ethtool.c  hw.c	hw.h  main.c  Makefile	reg.h

root@pve:~# ls /home/alx-wol
dkms-adder  install.sh	       Makefile        patches	  remove.sh  sources.txt
dkms.conf   kernelpatching.md  other_examples  README.md  scripts
```

I'm in China, when I run "git clone" command, it's always fail. and I have no idea what should I do next. please help me from here.

Should I run "mkdir /usr/src/alx-6.1"? I'm even no idea which version number should I use, the kernel version? or the patch version?
when I run "sh install.sh", it seems report a fail error.
And I found only a .patch file, where can I find other file in this topic says:
https://www.linuxquestions.org/questions/slackware-14/alx-wol-working-in-6-1-x-4175722247/#post6518786
I can't understand DKMS too, what should I write into Makefile, dkms.conf, source.txt?
I googled for these answers takes several days, but totally confuse me.
Tell me step by step, please.
Thank you very much.

**Comment by AndiWeiss** [comment]
Hi there, let's see if I can help.

You write: 'when I run "git clone" command, it's always fail'
Based on what I've read git should work fine in China.
But after reading your comments I strongly recommend to do a new, clean installation of proxmox before walking through my hints.

Please try:
- open a terminal and type all following commands in the terminal
- `git clone https://github.com/AndiWeiss/alx-wol.git`
After that there should be a directory `alx-wol`
- `cd alx-wol`
- `git checkout proxmox`
After that you have my alx-wol as source.

In case of proxmox you have to install some packages.

Do you have a proxmox subscription?
If no:
To be able to install the package you have to modify your file `/etc/apt/sources.list`:
`sudo echo "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription" >> /etc/apt/sources.list`
if yes:
continue

Now you can install the linux header package of proxmox together with some other packages:
`sudo apt install dkms build-essential proxmox-default-headers`

After that there is the last thing:
`sudo ./install.sh`

This script should do everything what is required.

There's one point I don't know:
There is a script included which downloads the original kernel sources from kernel.org.
Hopefully that works in China, too.

Looking forward to your report.
In case of any error please post the complete error message. Otherwise it's hard to check what's going on.

**Comment by arizuka** [comment]
Thank you very much, and sorry for sorry for the slow reply.
I ran your program two times, maybe script, forgive me that I don't know what is better to call.
The 1st time, I was ran as a remote connection. and I log session:
```
root@pve:/home/alx-wol# ./install.sh
2024-09-06 17:07:08 URL:https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/scripts/extract-vmlinux?h=v6.8 [1695/1695] -> ".temp/extract-vmlinux" [1]
#### using kernel version 6.8.12 ####
#### kernel was compiled with gcc 12.2.0 ####
Sign command: /lib/modules/6.8.12-1-pve/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Certificate or key are missing, generating self signed certificate for MOK...
#### using kernel version 6.8.12 ####
#### kernel was compiled with gcc 12.2.0 ####
#### using /usr/bin/x86_64-linux-gnu-gcc-12 to compile module ####
Creating symlink /var/lib/dkms/alx-wol/2.1.1/source -> /usr/src/alx-wol-2.1.1

Running the pre_build script:
2024-09-06 17:07:15 URL:https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/net/ethernet/atheros/alx?h=v6.8.12 [1178] -> "/var/lib/dkms/alx-wol/2.1.1/build/alx" [1]
2024-09-06 17:07:16 URL:https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/net/ethernet/atheros/alx/Makefile?h=v6.8.12 [101/101] -> "/var/lib/dkms/alx-wol/2.1.1/build/alx/Makefile" [1]
2024-09-06 17:07:19 URL:https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/net/ethernet/atheros/alx/alx.h?h=v6.8.12 [3420/3420] -> "/var/lib/dkms/alx-wol/2.1.1/build/alx/alx.h" [1]
2024-09-06 17:07:23 URL:https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/net/ethernet/atheros/alx/ethtool.c?h=v6.8.12 [8860/8860] -> "/var/lib/dkms/alx-wol/2.1.1/build/alx/ethtool.c" [1]
2024-09-06 17:07:25 URL:https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/net/ethernet/atheros/alx/hw.c?h=v6.8.12 [32348/32348] -> "/var/lib/dkms/alx-wol/2.1.1/build/alx/hw.c" [1]
2024-09-06 17:07:27 URL:https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/net/ethernet/atheros/alx/hw.h?h=v6.8.12 [19294/19294] -> "/var/lib/dkms/alx-wol/2.1.1/build/alx/hw.h" [1]
2024-09-06 17:07:31 URL:https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/net/ethernet/atheros/alx/main.c?h=v6.8.12 [48528/48528] -> "/var/lib/dkms/alx-wol/2.1.1/build/alx/main.c" [1]
2024-09-06 17:07:33 URL:https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/net/ethernet/atheros/alx/reg.h?h=v6.8.12 [29154/29154] -> "/var/lib/dkms/alx-wol/2.1.1/build/alx/reg.h" [1]
patching file alx/ethtool.c
Hunk #1 succeeded at 320 (offset -1 lines).
patching file alx/hw.c
patching file alx/hw.h
patching file alx/main.c
Hunk #1 succeeded at 1068 (offset -1 lines).
Hunk #2 succeeded at 1371 (offset -1 lines).
Hunk #3 succeeded at 1927 (offset -2 lines).
Hunk #4 succeeded at 1970 (offset -4 lines).
Hunk #5 succeeded at 2046 (offset -4 lines).
Hunk #6 succeeded at 2098 (offset -4 lines).
Hunk #7 succeeded at 2154 (offset -4 lines).

Building module:
Cleaning build area...
make -j4 KERNELRELEASE=6.8.12-1-pve -j4 KERNELRELEASE=6.8.12-1-pve -C /lib/modules/6.8.12-1-pve/build M=/var/lib/dkms/alx-wol/2.1.1/build HOSTCC=/usr/bin/x86_64-linux-gnu-gcc-12 CC=/usr/bin/x86_64-linux-gnu-gcc-12....
Signing module /var/lib/dkms/alx-wol/2.1.1/build/alx/alx.ko
Cleaning build area...

alx.ko:
Running module version sanity check.
 - Original module
 - Installation
   - Installing to /lib/modules/6.8.12-1-pve/updates/dkms/

Running the post_install script:

Socket error Event: 32 Error: 10053.
Connection closing...Socket close.

Connection closed by foreign host.

Disconnected from remote host(G4560T PVE) at 17:08:27.
```
Then I don't know what stats of my computer, because my computer doesn't have a monitor connected.

2nd time, I linked monitor, keyboard, reinstall PVE, follow your steps, then I got a "success" from display output. But no network, when I ran `ethtool enp1s0`, I got something like:
```
	Speed: Unknown
	Duplex: Unknown
	Auto-negotiation: on
	Port: Twisted Pair
	PHYAD: 0
	Transceiver: internal
	MDI-X: Unknown
	Supports Wake-on: pg
	Wake-on: pg
        Current message level: 0x000060e4 (24804)
                               link ifup rx_err tx_err hw wol
	Link detected: yes
```

After that, I forgot to test `systemctl restart networking` was working or not, I reboot my computer, then everything looks fine. The computer can be waked up, and no `ethtool -s enp1s0 wol g`  is required. I tested `poweroff` and wake it up twice. maybe add a command of restart NIC is better.

By the way, you are right, "git clone" command works fine, and I got another question, is the "git clone" command needs run in /usr/src , or it's can run in anywhere? 1st time i tried patch driver, I was run `git clone` in /home, 2nd time I run this in /usr/src.

Do you mind if I translate this topic into Chinese, post in my blog, and introduce this project? It's so great.
Thank you again for your enthusiasm.

**Comment by AndiWeiss** [comment]
Hi there,
the log looks exactly as it shall look.
The point why you don't see the final result in the first log is:
After successful creation of the module my scripting exchanges the active module by the new one.
For doing that it has to shut down this network interface.
So if you do this by a remote connection over this network this connection is interrupted.
Doing this remote in principle is as if you cut the branch of a tree where you're sitting on :-)

I'm a bit puzzled that the network doesn't start up automatically.
The plan is that during the installation the connection gets lost for a short time but comes back automatically.
I'll take a look for that.
Maybe it's a good idea to add a parameter to tell that the driver shall not be exchanged - then one can do the installation via remote, too.

I have some plans for the future where I'm going to change the scripting.
But:
I only change the scripting.
The real "software" - the driver - will stay the same.
What happens during the installation:
My scripting collects some information of your linux system. Mainly the kernel version and the compiler which has been used and which compilers are available.
With this information the scripting fetches the original kernel sources of the kernel version, patches them and builds them.
As everything is scripting around the detection of the kernel version nothing will change as long as my patches match the sources.

Concerning the 'git clone':
In linux you always do everything as a user. And each user has its own so called home directory.
Git is a tool used by a user, so you should call it somewhere in your home directory. Where exactly doesn't matter.
To be honest I don't have the details of Proxmox in mind - if you have to use 'root' here instead of a user you should call git somewhere in /root.
The scripting - to be more precise: install.sh - does the installation in /usr/src.

Concerning the translation:
Sure, this is completely free software. Feel free to do whatever you like.

As it seems that you're no familar with git:
Just add a hint to check for new versions also on different branches.
Currently the scripting supports Ubuntu and Debian on the branch 'master'.
But there is the branch 'proxmox' where this system has been added and 'arch_linux' where that distribution has been added.
In the future I'm going to combine all of that again.
And maybe I add further Distributions, too :-)

**Comment by arizuka** [comment]
I'm posted blog here:
https://blog.csdn.net/2301_80141848/article/details/142080178?spm=1001.2014.3001.5502
Hopefully more people will be helped.
