### ISSUE TITLE
6.5 kernel

### ISSUE THREAD

**Issue by dga4130-renato** [AndiWeiss/alx-wol#5]
hello,
kernel 6.5 is complaining about a different compiler version ..seems needs gcc 13.2 instead of 13.1
is it possible to fix that ?

**Comment by AndiWeiss** [comment]
I'll take a look.
Which system are you using?

**Comment by dga4130-renato** [comment]
Ubuntu 23.04... on October 23.10 will be out and the GCC there will be 13.2
..that is because kernel 6.5 was complied with 13.2 ...
Installing GCC 13.2 is a problem on 23.04 cause too many dependency's

Il ven 1 set 2023, 23:50 AndiWeiss ***@***.***> ha scritto:

**Comment by AndiWeiss** [comment]
That's no so easy.
It seems that up to now there is no 'official' gcc 13.2 for ubuntu but their kernel images starting with 6.4.13 are compiled with that.
Up to that version gcc-12 works fine with that, but since then the linker complains about a not found glibc.
Currently I don't have a solution for this issue.
Maybe you can have a look here:
https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GNU%20Software/build-gcc
but I didn't try that. For sure you need to adapt my scripting, too.
I'll think a bit more about that.

**Comment by AndiWeiss** [comment]
I'm doing some tries right now.
I already found a possibility to check the compiler version used for the kernel.
Now I'm going to implement a search if that compiler is available and if yes use that one.
If this is implemented you "only" need to take care that the matching compiler is installed.
My current issue is: if the complete compiler version match is not find I need to do some kind of fallback.
Currently I'm thinking of taking the highest compiler version which has been found.
This still doesn't solve your issue as the ubuntu kernel needs gcc 13.2 which is not yet available.
But if you are able to build that compiler it would work.
And - sorry, but I need some more time for that.

**Comment by AndiWeiss** [comment]
UPDATE:
Problem is NOT the gcc 13.2.
Problem is that the new kernel has a dependency on libc6 2.38 while ubuntu only has libc6 2.37 installed.
Replacing libc 'by hand' is too much effort because of the large amount of dependencies.
What you can do if you want to use a kernel >= 6.4.13:
You can compile the kernel by yourself.
Explanations for that can easily be found with the search machine of your choice.

**Comment by dga4130-renato** [comment]
Yes I saw that , will have to wait October and Ubuntu 23.10 that comes with
the new libc and depending files.
No worth compiling , just have to wait a few weeks 👍👍👍

Il dom 10 set 2023, 18:58 AndiWeiss ***@***.***> ha scritto:
